DEVICE_PATH := device/infinix/X6886

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_2ND_ARCH :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_CPU_VARIANT :=

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6789
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := mt6789

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_TAGS_OFFSET := 0x07c08000
BOARD_RAMDISK_OFFSET := 0x11088000
BOARD_DTB_OFFSET := 0x07c08000
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_IMAGE_NAME := Image.gz

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt/dtb
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)

# Vendor boot
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
TARGET_RECOVERY_RAMDISK_OUT := $(OUT)/vendor_ramdisk

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    lk \
    odm \
    odm_dlkm \
    product \
    system \
    system_ext \
    vbmeta_system \
    vbmeta_vendor \
    vendor \
    vendor_boot \
    vendor_dlkm

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_VBMETA_SYSTEM := system system_ext product
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 2

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := 9122611200
BOARD_MAIN_PARTITION_LIST := system system_ext vendor product odm odm_dlkm vendor_dlkm

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := erofs

# Dynamic partitions
BOARD_DYNAMIC_PARTITION_ENABLE := true

# Virtual A/B
BOARD_VIRTUAL_AB_ENABLE := true
BOARD_VIRTUAL_AB_COMPRESSION := true

# Userdata
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# TWRP / OrangeFox specific
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true
TW_HAS_NO_RECOVERY_PARTITION := true
TW_FORCE_CPUINFO_FOR_BATTERY := true
RECOVERY_SDCARD_ON_DATA := true
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_DEFAULT_BRIGHTNESS := 10
TW_MAX_BRIGHTNESS := 255

# Crypto
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_METADATA_PARTITION := true
PLATFORM_VERSION := 16.1.0
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31

# Debug
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# ========== OUR ADDITIONS ==========

# 64-bit support
TARGET_SUPPORTS_64_BIT_APPS := true

# Display - OrangeFox R12.1
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2408
TW_ROTATION := 0
TW_NO_SCREEN_BLANK := true
TW_EXCLUDE_TWRP_DEFAULT_KEYMAP := true
OF_SCREEN_H := 2408
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 70
OF_STATUS_INDENT_RIGHT := 70
OF_CLOCK_POS := right
OF_ALLOW_DISABLE_NAVBAR := 1
OF_HIDE_NOTCH := 1
OF_DISPLAY_120HZ_SUPPORT := 1
OF_DISPLAY_144HZ_SUPPORT := 1

# OrangeFox Features
OF_USE_LZMA_COMPRESSION := 1
OF_USE_ICON_BITMAP := 1
OF_THEME := dark

# Flashlight
OF_FL_PATH1 := /sys/class/leds/torch-light/brightness
OF_FL_PATH2 := /sys/class/leds/torch-light1/brightness

# Encryption - Auto decrypt on boot
OF_FIX_DECRYPTION_ON_DATA_MEDIA := 1
OF_KEEP_DM_VERITY_FORCE_ENCRYPTION := 1
OF_SKIP_DECRYPTION := 1
OF_SKIP_FBE_DECRYPTION := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_FORCE_DECRYPT_ON_BOOT := 1

# Security
OF_ADVANCED_SECURITY := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1

# Misc OrangeFox
OF_NO_MIUI_PATCH_WARNING := 1
OF_NO_TREBLE_CHECK := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_UNMOUNT_DATA_FIRST := 1

# A/B & Vendor boot
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# MTP & USB
TW_INCLUDE_MTP := true
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_MODEM_HARDWARE_KEY := true

# Fastbootd
TW_INCLUDE_FASTBOOTD := true

# FRP
TW_INCLUDE_FRP := true

# KernelSU
TW_INCLUDE_KERNELSU := true

# File system tools
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_EXFAT := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_PYTHON := true

# Debug
TW_EXTRA_EVENT_LOG_ENABLED := true
TW_INCLUDE_CRYPTO_UMS := true
TW_INCLUDE_FB2PNG := true
TW_CUSTOM_CPU_TEMP_PATH := /sys/class/thermal/thermal_zone6/temp
TW_CUSTOM_BATTERY_PATH := /sys/class/power_supply/mtk_battery

# Misc
TW_USE_NEW_MINADBD := true
TW_NO_LEGACY_PROPS := true
TW_DATA_RECOVERY := true
TARGET_USES_LOGD := true
BOARD_SUPPRESS_SECURE_ERASE := true
