DEVICE_PATH := device/transsion/X6886

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6789
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := mt6789
TARGET_BOARD_PLATFORM_GPU := mali-g52 mc1

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.hardware=mt6789
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x11b00000
BOARD_TAGS_OFFSET := 0x07c80000
BOARD_DTB_OFFSET := 0x07c80000
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_IMAGE_NAME := Image.gz

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img

BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)

# Vendor boot
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
TARGET_RECOVERY_RAMDISK_OUT := $(OUT_DIR)/vendor_ramdisk

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    lk \
    odm_dlkm \
    product \
    system \
    system_ext \
    vbmeta_system \
    vbmeta_vendor \
    vendor \
    vendor_boot \
    vendor_dlkm

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_VBMETA_SYSTEM := system system_ext product
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 2

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMAGE_PARTITION_SIZE := 8388608
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := infinix_dynamic_partitions
BOARD_INFINIX_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_INFINIX_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext vendor product odm_dlkm vendor_dlkm \
    tr_mi tr_theme tr_region tr_company tr_carrier tr_product tr_preload tr_overlayfs

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4

# Dynamic partitions
BOARD_DYNAMIC_PARTITION_ENABLE := true

# Virtual A/B
BOARD_VIRTUAL_AB_ENABLE := true
BOARD_VIRTUAL_AB_COMPRESSION := true

# Userdata
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs

# Metadata
BOARD_USES_METADATA_PARTITION := true

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Copy out paths
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM := system
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
TARGET_COPY_OUT_ODM_DLKM := odm_dlkm

# TWRP / OrangeFox specific
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true
TW_HAS_NO_RECOVERY_PARTITION := true
TW_FORCE_CPUINFO_FOR_BATTERY := true
RECOVERY_SDCARD_ON_DATA := true
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"

# Flashlight Support

# Settings Persistence (/data/recovery)
TW_DATA_RECOVERY := true

# OrangeFox Branding - Team B E R U
FOX_BUILD_TYPE := Stable
FOX_MAINTAINER := BERU
FOX_MAINTAINER_PATCH_VERSION := 1
FOX_VARIANT := AOSP
FOX_DEVICE := X6886
FOX_SKIP_CHECK := true

OF_USE_LZMA_COMPRESSION := 1
OF_USE_ICON_BITMAP := 1
OF_THEME := dark
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 10
TW_INCLUDE_MTP := true
OF_FL_PATH2 := /sys/class/leds/torch-light1/brightness
OF_UNMOUNT_DATA_FIRST := 1
TW_USE_FSCRYPT_POLICY := 1

# OrangeFox UI/Theme - Material Design
OF_SCREEN_H := 2408
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 70
OF_STATUS_INDENT_RIGHT := 70
OF_CLOCK_POS := right
OF_ALLOW_DISABLE_NAVBAR := 1
OF_HIDE_NOTCH := 1

# Flashlight
OF_FL_PATH1 := /sys/class/leds/torch-light/brightness

# Display - 120Hz + 144Hz support

# Advanced Features
OF_ADVANCED_SECURITY := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := 1
OF_FIX_DECRYPTION_ON_DATA_MEDIA := 1
OF_KEEP_DM_VERITY_FORCE_ENCRYPTION := 1
OF_SKIP_DECRYPTION := 1
OF_SKIP_FBE_DECRYPTION := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_NO_MIUI_PATCH_WARNING := 1
OF_NO_TREBLE_CHECK := 1
OF_PATCH_VBMETA_FLAG := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1

# Better partition support
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1

# FRP Addon Support
TW_INCLUDE_FRP := true

# KernelSU Support
TW_INCLUDE_KERNELSU := true

# Crypto
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_CRYPTO_USE_SYSTEM_VOLD := true
TW_CRYPTO_USE_FBE := false
BOARD_SUPPRESS_SECURE_ERASE := true
TW_CRYPTO_SYSTEM_VOLD := true

# Extra tools
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_EXFAT := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_PYTHON := true
TW_EXTRA_EVENT_LOG_ENABLED := true
TW_INCLUDE_CRYPTO_UMS := true

# Screen settings  
TW_ROTATION := 0
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_BLANK := true
TW_USE_TOOLBOX := true
TW_EXCLUDE_TWRP_SNAPSHOT := false

# ADB
TW_INCLUDE_FASTBOOTD := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_MODEM_HARDWARE_KEY := true

# Misc
TW_NO_LEGACY_PROPS := true
TW_USE_NEW_MINADBD := true
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_INCLUDE_FB2PNG := true
TW_CUSTOM_CPU_TEMP_PATH := /sys/class/thermal/thermal_zone6/temp
TW_CUSTOM_BATTERY_PATH := /sys/class/power_supply/mtk_battery
PLATFORM_VERSION := 16.1.0
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31

# Debug
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
