export FOX_BUILD_TYPE=Stable
export FOX_MAINTAINER=BERU
export FOX_MAINTAINER_PATCH_VERSION=1
export FOX_VARIANT=AOSP
export FOX_DEVICE=X6886
export FOX_SKIP_CHECK=true
export FOX_PATCH_VBMETA_FLAG=1
